// ExamGo data layer
// Structured from VIT B.Tech Sem 1 & Sem 2 CAT/FAT question papers (2025-2026)

const SUBJECTS = [
  {
    code: "BAENG101",
    name: "Technical English Communication",
    semester: 1,
    school: "School of Social Sciences and Languages",
    color: "#8a4b2e",
    topicWeightage: [
      { topic: "Grammar — Concord (Subject-Verb Agreement)", weight: 95, frequency: "Every CAT1/CAT2/FAT" },
      { topic: "Grammar — Conditionals (all types)", weight: 92, frequency: "Every CAT1/CAT2/FAT" },
      { topic: "Definitions (1-2 sentence, technical vocabulary)", weight: 88, frequency: "Almost every paper" },
      { topic: "5 Cs of Communication (case studies)", weight: 85, frequency: "Very common in CAT1" },
      { topic: "Taxonomy of Technical Communication", weight: 80, frequency: "Common in CAT1" },
      { topic: "Reading Comprehension (inference + fact-based)", weight: 78, frequency: "Every paper" },
      { topic: "Tense correction / tense shifts", weight: 70, frequency: "Common in CAT2/FAT" },
      { topic: "Active ↔ Passive voice conversion", weight: 68, frequency: "Common in CAT2/FAT" },
      { topic: "Statement of Purpose (SOP) writing", weight: 55, frequency: "FAT only" },
      { topic: "Abstract writing (IMRaD)", weight: 52, frequency: "FAT only" },
      { topic: "Leadership styles / team roles / conflict management", weight: 60, frequency: "FAT, case-study heavy" },
      { topic: "Minutes of Meeting drafting", weight: 35, frequency: "Occasional CAT1" },
    ],
    predictedImportant: [
      "Concord paragraph correction (5 errors) — appears in literally every paper across every slot; near-certain in next CAT/FAT.",
      "Conditional clause fill-in-the-blanks (mixed types) — paired with concord almost always; expect 5 fill-ups.",
      "5 Cs of Communication applied to a workplace case study (email/WhatsApp message/circular) — dominant CAT1 question type.",
      "Definitions of 5 technical/abstract words — a fixed-format question across nearly all slots, easy guaranteed marks.",
      "Reading comprehension passage on workplace/technology/communication themes with 4 mixed inferential + factual questions.",
    ],
    papers: [
      { id: "beng-cat1-a1", examType: "CAT1", slot: "A1+TA1", semType: "Fall", faculty: "Prof. Marziya Begum", marks: 50, duration: "90 mins",
        questions: [
          { q: "Identify the most appropriate taxonomy of technical writing for a marketing document (wearable health tracker case); justify with features + one more example.", marks: 10, co: "CO2", bl: "BL2" },
          { q: "Draft Minutes of the Meeting for a given Tech Symposium preparatory meeting scenario, as Recording Secretary.", marks: 10, co: "CO2", bl: "BL3" },
          { q: "Rewrite a poor smartwatch description into a precise, professional write-up with a suitable title.", marks: 10, co: "CO2", bl: "BL2" },
          { q: "10 MCQs covering tenses (future perfect continuous), conditionals, subject-verb agreement, active/passive voice.", marks: 10, co: "CO3", bl: "BL3" },
          { q: "Identify grammatical errors in a paragraph, underline and rewrite correctly.", marks: 10, co: "CO3", bl: "BL2" },
        ]},
      { id: "beng-cat1-b1", examType: "CAT1", slot: "B1+TB1", semType: "Winter", faculty: "Yadamala Sreenivasulu et al. (multi-faculty)", marks: 50, duration: "90 mins",
        questions: [
          { q: "Explain Taxonomy of Technical Communication — classify into 5 categories with definition + workplace example each.", marks: 10, co: "CO2", bl: "BL2" },
          { q: "Analyse a WhatsApp CAT-1 reminder message using the 5Cs of Communication (5 problems); rewrite it clearly and courteously.", marks: 10, co: "CO2", bl: "BL3" },
          { q: "(a) Correct 5 concord errors in a calibration-readings paragraph. (b) Complete 5 conditional clauses.", marks: 10, co: "CO3", bl: "BL2/BL3" },
          { q: "Reading comprehension on technical writing & verification — 4 questions (definition, actions, inference, example).", marks: 10, co: "CO4", bl: "BL3" },
          { q: "Define 5 words in 1-2 sentences: Textbook, Citation, Plagiarism, Summary, Evidence.", marks: 10, co: "CO4", bl: "BL3" },
        ],
        hasAnswerKey: true },
      { id: "beng-cat1-b2", examType: "CAT1", slot: "B2+TB2", semType: "Winter", faculty: "Dr. Anu Baisel", marks: 50, duration: "90 mins",
        questions: [
          { q: "Explain the nature of technical writing vs literary/creative writing (purpose, audience, style).", marks: 10, co: "CO2", bl: "BL3" },
          { q: "Case study (NovaTech hybrid work reporting system): identify communication gaps + channel choice impact.", marks: 10, co: "CO3", bl: "BL3" },
          { q: "(a) Spot 5 errors in an online-learning paragraph. (b) Fill 5 conditional clauses.", marks: 10, co: "CO2/CO3", bl: "BL2/BL3" },
          { q: "Define 5 words in one sentence: Privacy, Leadership, Gratitude, Globalization, Entrepreneurship.", marks: 10, co: "CO2", bl: "BL3" },
          { q: "Reading comprehension on digital communication & workplace relationships — 4 questions.", marks: 10, co: "CO3", bl: "BL2" },
        ]},
      { id: "beng-cat1-c1", examType: "CAT1", slot: "C1+TC1", semType: "Winter", faculty: "Senguttuvan M et al.", marks: 50, duration: "90 mins",
        questions: [
          { q: "Discuss precision, intent, and audience awareness in technical writing.", marks: 10, co: "CO2", bl: "BL2" },
          { q: "BrightMart business communication case study — apply 5Cs, identify 3 failures, rewrite core message.", marks: 10, co: "CO6", bl: "BL2" },
          { q: "(a) Correct subject-verb agreement errors in equipment passage. (b) Fill 5 conditional clauses.", marks: 10, co: "—", bl: "BL1" },
          { q: "Reading comprehension on Augmented Reality — 4 questions.", marks: 10, co: "—", bl: "BL2" },
          { q: "Define 5 words: Globalization, Sustainability, Ideology, Multiculturalism, Ethics.", marks: 10, co: "—", bl: "BL3" },
        ]},
      { id: "beng-cat1-c2", examType: "CAT1", slot: "C2+TC2", semType: "Winter", faculty: "Dr. Shivshankar Rajmohan, Dr. Prajeesh Tomy", marks: 50, duration: "90 mins",
        questions: [
          { q: "Explain how branches of technical writing differ (peer-oriented vs user-oriented), with examples.", marks: 10, co: "CO2", bl: "BL2" },
          { q: "Anvaya Mobility case study (multi-stakeholder email) — analyse 5Cs violations + propose 3 revisions.", marks: 10, co: "CO2", bl: "BL3" },
          { q: "Section A: 5 concord errors in governance review paragraph. Section B: 5 conditional fill-ins.", marks: 10, co: "CO3", bl: "BL2" },
          { q: "Apply precise/clear writing to define 5 terms (50 words each): Blog, University, Hard disk, Chatbot, Mobile phone.", marks: 10, co: "CO4", bl: "BL3" },
          { q: "Reading comprehension on preserving indigenous cultures — 4 inference-based questions.", marks: 10, co: "CO4", bl: "BL3" },
        ]},
      { id: "beng-cat1-d1", examType: "CAT1", slot: "D1+TD1", semType: "Winter", faculty: "Prof. Sreekala U", marks: 50, duration: "90 mins",
        questions: [
          { q: "Elaborate key aspects and divisions in technical communication with examples.", marks: 10, co: "CO2", bl: "BL3" },
          { q: "Compose an email as a manager regarding updated leave policy & approval procedure.", marks: 10, co: "CO2", bl: "BL4" },
          { q: "Rewrite a poorly written rice cooker user manual applying 5Cs, specifying each error type.", marks: 10, co: "CO2", bl: "BL4" },
          { q: "Concord: 10 fill-in-the-blank sentences with correct verb forms (subject-verb agreement).", marks: 10, co: "CO3", bl: "BL3" },
          { q: "Conditionals: 10 fill-in-the-blanks across zero/first/second/third/mixed conditional types.", marks: 10, co: "CO3", bl: "BL3" },
        ]},
      { id: "beng-cat1-g1-fall", examType: "CAT1", slot: "G1+TG1", semType: "Fall", faculty: "Anil Premraj J et al. (multi-faculty)", marks: 50, duration: "90 mins",
        questions: [
          { q: "Explain 5 key characteristics of technical writing with examples.", marks: 10, co: "CO2", bl: "BL2" },
          { q: "Aarav Foods case study — apply business communication strategies; explain upward/horizontal communication.", marks: 10, co: "CO2", bl: "BL3" },
          { q: "Identify & correct concord errors in a 'Nature' paragraph (underline + rewrite).", marks: 5, co: "CO3", bl: "BL2" },
          { q: "Complete 5 conditional sentences (Type 0/I/II/III).", marks: 5, co: "CO3", bl: "BL2" },
          { q: "Define 5 words: Communication, Technology, Information, Management, Innovation.", marks: 10, co: "CO4", bl: "BL3" },
          { q: "Reading comprehension on hybrid/remote work models — 4 inference + fact questions.", marks: 10, co: "CO4", bl: "BL3" },
        ]},
      { id: "beng-cat2-g1", examType: "CAT2", slot: "G1+TG1", semType: "Winter", faculty: "Dr. Vijayakumar M et al. (multi-faculty)", marks: 50, duration: "90 mins",
        questions: [
          { q: "Identify tense shifts in a biotech paragraph; rewrite precisely with corrections underlined.", marks: 5, co: "CO3", bl: "BL2" },
          { q: "Rewrite an AI cybersecurity passage in passive voice.", marks: 5, co: "CO3", bl: "BL2" },
          { q: "Write a Statement of Purpose (SOP) for MS Data Science at Oxford (200 words).", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Prepare a 200-word abstract for a given research article on renewable energy adoption.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Civil engineering team case study — explain leadership strategies' contribution to team building.", marks: 10, co: "CO6", bl: "BL3" },
          { q: "Software dev/client negotiation case study — explain how negotiation resolved the conflict.", marks: 10, co: "CO6", bl: "BL3" },
        ]},
      { id: "beng-fat-b1", examType: "FAT", slot: "B1+TB1", semType: "April 2026", faculty: "Multi-faculty pool", marks: 100, duration: "3 hours",
        questions: [
          { q: "Define 'User Manual' in technical taxonomy with examples.", marks: 10, co: "CO2", bl: "BL2" },
          { q: "Yahoo data breach case — describe importance of 'correctness' and 'completeness' in technical writing.", marks: 10, co: "CO2", bl: "BL2" },
          { q: "(A) Correct SVA errors in a cricket-themed paragraph. (B) Correct tense errors in exam-malpractice paragraph.", marks: 10, co: "CO3", bl: "BL3" },
          { q: "(A) 5 conditional fill-ins. (B) Convert a Blood Donation camp passage Active → Passive.", marks: 10, co: "CO3", bl: "BL2" },
          { q: "Define 5 words: Webinar, Brandish, Inconspicuous, Orthodox, Philanthropic.", marks: 10, co: "CO4", bl: "BL3" },
          { q: "Climate change passage — 4 comprehension questions OR research paper parts short notes.", marks: 10, co: "CO4", bl: "BL3" },
          { q: "Write an Abstract for a remote-work-productivity research paper OR write an SOP for postgrad admission.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Write a 500-word Australian student visa SOP (academic background, financial support, return intent).", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Explain best leadership style for a normal workday with example.", marks: 10, co: "CO6", bl: "BL3" },
          { q: "Belbin Team Roles case study (Thintext Solutions) — diagnose team composition problem + fix.", marks: 10, co: "CO6", bl: "BL3" },
          { q: "Marketing vs Sales conflict case study (NexaPharma) — root cause + mediation resolution.", marks: 10, co: "CO6", bl: "BL3" },
        ]},
      { id: "beng-fat-b2", examType: "FAT", slot: "B2+TB2", semType: "April 2026", faculty: "Multi-faculty pool", marks: 100, duration: "3 hours",
        questions: [
          { q: "Defend: formal vs informal report differs in structure, purpose, audience.", marks: 10, co: "CO2", bl: "BL2" },
          { q: "Discuss importance of each of the 5 C's of a technical report with examples.", marks: 10, co: "CO2", bl: "BL2" },
          { q: "(A) Correct 5 concord errors in a fleet-of-ships paragraph. (B) Correct 5 tense errors in an AI seminar paragraph.", marks: 10, co: "CO3", bl: "BL3" },
          { q: "(A) 5 conditional fill-ins. (B) Convert an FDP-announcement paragraph Active ↔ Passive.", marks: 10, co: "CO3", bl: "BL2" },
          { q: "Define 5 words: Perseverance, Harmony, Empathy, Discipline, ChatGPT.", marks: 10, co: "CO4", bl: "BL3" },
          { q: "Reading comprehension (Raghav/farmer passage) — 4 questions OR IMRaD format analysis.", marks: 10, co: "CO4", bl: "BL3" },
          { q: "Write a 100-word abstract for a physical-exercise-and-concentration research article OR an admissions SOP.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Critically analyze autocratic, democratic, laissez-faire leadership styles with examples.", marks: 10, co: "CO6", bl: "BL3" },
          { q: "Management student team case study — analyze team roles + role clarity improvements.", marks: 10, co: "CO6", bl: "BL3" },
          { q: "Consulting firm conflict case study (workload imbalance) — analyze causes + conflict management strategies.", marks: 10, co: "CO6", bl: "BL3" },
        ]},
    ],
  },
  {
    code: "BAEEE101",
    name: "Basic Engineering",
    semester: 1,
    school: "School of Electrical Engineering / School of Mechanical Engineering",
    color: "#1f5c4a",
    topicWeightage: [
      { topic: "Network theorems — Mesh/Nodal analysis", weight: 90, frequency: "Every electrical-stream CAT1" },
      { topic: "Superposition theorem", weight: 88, frequency: "Every electrical-stream CAT1" },
      { topic: "Thevenin's theorem", weight: 86, frequency: "Every electrical-stream CAT1" },
      { topic: "AC circuits — series R-L-C analysis (impedance, p.f., power)", weight: 80, frequency: "Common in CAT1" },
      { topic: "DC machines / transformers / induction motors (theory)", weight: 65, frequency: "One Q per paper, CAT1" },
      { topic: "Engineering Drawing — Dimensioning per BIS standards", weight: 92, frequency: "Every Mech-stream CAT (1 & 2)" },
      { topic: "Orthographic projections (first-angle method)", weight: 90, frequency: "Every Mech-stream CAT (1 & 2)" },
      { topic: "Projections of solids (pyramids/prisms inclined to VP/HP)", weight: 85, frequency: "Every Mech-stream CAT (1 & 2)" },
      { topic: "Isometric views (cone, cylinder, etc.)", weight: 82, frequency: "Every Mech-stream CAT (1 & 2)" },
      { topic: "Sand casting process & pattern allowances", weight: 78, frequency: "Common, both CATs" },
      { topic: "Extrusion / welding / casting defects (manufacturing)", weight: 50, frequency: "Occasional in CAT2" },
    ],
    predictedImportant: [
      "Mesh or nodal analysis on a 3-loop resistive circuit — guaranteed Q1/Q2 across nearly all electrical-stream slots.",
      "Superposition theorem with mixed voltage + current sources — second most common circuits question.",
      "Thevenin's equivalent + load current calculation — appears in almost every CAT1 paper.",
      "Series R-L-C AC circuit: find Z, I, p.f., real/reactive power — standalone Q4 pattern in every slot.",
      "BIS-standard dimensioning correction exercise — appears in literally every Mech-stream paper (CAT1 and CAT2), the single most predictable question in this subject.",
      "Orthographic projection (front/top/side view) from an isometric figure — guaranteed in every Mech-stream CAT.",
      "Sand casting allowances (shrinkage, draft, machining) — recurring CAT1/CAT2 theory question.",
    ],
    papers: [
      { id: "beee-cat1-a2", examType: "CAT1", slot: "A2+TA2", semType: "Fall", faculty: "Dr K Sathish Kumar et al.", marks: 50, duration: "90 mins", track: "Electrical",
        questions: [
          { q: "Calculate mesh currents for a 3-mesh resistive circuit.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Use superposition theorem to find current i in a mixed-source circuit.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Draw the Thevenin's equivalent circuit for a given network.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Series R-L-C (12Ω, 0.15H, 100µF) at 100V/50Hz — find Z, I, voltages, phase difference.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Explain construction of single-phase transformer with diagram.", marks: 10, co: "CO1", bl: "BL1" },
        ]},
      { id: "beee-cat1-b1", examType: "CAT1", slot: "B1+TB1", semType: "Fall", faculty: "Dr. Naveen Kumar et al. (multi-faculty)", marks: 50, duration: "90 mins", track: "Electrical",
        questions: [
          { q: "Find current through 4Ω resistor using mesh analysis.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Find current through 10Ω resistor using superposition theorem.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Find current through 8Ω resistor using Thevenin's theorem.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "R-L-C series circuit, 100V/50Hz, 10A leading current — find L, R, C, p.f., voltage across C, real power.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Discuss working principle of single-phase induction motor — why not self-starting; applications.", marks: 10, co: "CO1", bl: "BL2" },
        ]},
      { id: "beee-cat1-b2", examType: "CAT1", slot: "B2+TB2", semType: "Fall", faculty: "Jabeena A et al.", marks: 50, duration: "90 mins", track: "Electrical",
        questions: [
          { q: "Determine current I using nodal voltage analysis.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Determine current i using superposition theorem.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Find current through 6Ω resistor (added between A-B) using Thevenin's theorem.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Instantaneous voltage v(t)=300sin314t across R-L-C series — RMS current, phase, i(t), voltages, p.f., P & Q.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "(a) Function of commutator/brushes/armature in DC machine. (b) Transformer working principle. (c) Applications of DC series & induction motor.", marks: 10, co: "CO1", bl: "BL2" },
        ]},
      { id: "beee-cat1-c1", examType: "CAT1", slot: "C1+TC1", semType: "Fall", faculty: "Mrutunjaya Panda et al.", marks: 50, duration: "90 mins", track: "Electrical",
        questions: [
          { q: "Use node voltage method to find power dissipated in 6Ω resistor.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Determine current through 24Ω resistor using Thevenin's theorem.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Find current through 3Ω resistor using superposition theorem.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Transmission line load problem (4+j2Ω line impedance) — find real & reactive power at source, line, load.", marks: 10, co: "CO1", bl: "BL2" },
          { q: "(a) Working principle & construction of DC motor. (b) Applications of DC motor.", marks: 10, co: "CO1", bl: "BL2" },
        ]},
      { id: "beee-cat1-d2", examType: "CAT1", slot: "D2+TD2", semType: "Fall", faculty: "Senthil Kumar M et al.", marks: 50, duration: "90 mins", track: "Mechanical/Drawing",
        questions: [
          { q: "Identify incorrect dimensioning practices; redraw per BIS standards.", marks: 10, co: "CO3", bl: "BL1" },
          { q: "First-angle orthographic projections (front/top/side) of a machine component with BIS dimensions.", marks: 10, co: "CO3", bl: "BL2" },
          { q: "Projections of a pentagonal pyramid (40mm base, 60mm height) inclined 35° to VP, resting on HP.", marks: 10, co: "CO3", bl: "BL2" },
          { q: "Isometric view of a cone (50mm base diameter, 65mm height) resting on HP.", marks: 10, co: "CO3", bl: "BL2" },
          { q: "(a) Sand-casting process steps + cross-sectional sketch. (b) Extrusion process + applications.", marks: 10, co: "CO4", bl: "BL2" },
        ]},
      { id: "beee-cat1-e1", examType: "CAT1", slot: "E1+TE1", semType: "Fall", faculty: "Dr. Srimathi R et al. (multi-faculty)", marks: 50, duration: "90 mins", track: "Electrical",
        questions: [
          { q: "Use mesh analysis to find vab and i0 in a given circuit.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Use Thevenin's theorem to find equivalent circuit & load current.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "Use superposition theorem to find current through 23Ω resistor.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "(a) R-L-C series with 200µF cap at 200V/50Hz — Z, I, p.f., power. (b) RC circuit voltage across R & C.", marks: 10, co: "CO1", bl: "BL3" },
          { q: "(a) BJT CE configuration input/output characteristics circuit. (b) Zener diode as voltage regulator.", marks: 10, co: "CO1", bl: "BL2" },
        ]},
      { id: "beee-cat1-e2", examType: "CAT1", slot: "E2+TE2", semType: "Fall", faculty: "Dr. Vinoth Jebaraj A et al.", marks: 50, duration: "90 mins", track: "Mechanical/Drawing",
        questions: [
          { q: "Identify dimensioning errors in given figure; redraw per BIS standards.", marks: 10, co: "CO3", bl: "BL3" },
          { q: "Square pyramid (50mm base, 70mm axis) resting on HP, base side parallel to VP — top & front view.", marks: 10, co: "CO3", bl: "BL3" },
          { q: "First-angle projection: front view, top view, left-side view from a pictorial object.", marks: 10, co: "CO3", bl: "BL3" },
          { q: "Isometric view of a vertical cylinder (50mm dia, 60mm axis length).", marks: 10, co: "CO3", bl: "BL3" },
          { q: "(a) Types of pattern allowances in casting. (b) Consequences of neglecting shrinkage/draft allowance.", marks: 10, co: "CO4", bl: "BL2" },
        ],
        hasAnswerKey: true },
      { id: "beee-cat2-a1", examType: "CAT2", slot: "A1+TA1", semType: "Fall", faculty: "Dr. Senthil Kumar M et al.", marks: 50, duration: "90 mins", track: "Mechanical/Drawing",
        questions: [
          { q: "Redraw a 2D drawing with corrected dimensions per BIS standard.", marks: 10, co: "CO3", bl: "BL3" },
          { q: "First-angle orthographic projections of a given isometric object.", marks: 10, co: "CO3", bl: "BL5" },
          { q: "Isometric view of a cylinder (40mm base, 70mm height) resting on HP.", marks: 10, co: "CO3", bl: "BL4" },
          { q: "Projections of a pentagonal pyramid (35mm base, 70mm height), one side inclined 45° to VP.", marks: 10, co: "CO3", bl: "BL4" },
          { q: "Illustrate sand casting process with sketch; list pattern allowance types.", marks: 10, co: "CO4", bl: "BL3" },
        ]},
      { id: "beee-cat2-a2", examType: "CAT2", slot: "A2+TA2", semType: "Fall", faculty: "Multi-faculty (Mech)", marks: 50, duration: "90 mins", track: "Mechanical/Drawing",
        questions: [
          { q: "Draw & correct dimensions of a given 2D drawing in Aligned System.", marks: 10, co: "CO3", bl: "—" },
          { q: "Draw orthographic projection (FV/TV/RHS) for a given drawing.", marks: 10, co: "CO3", bl: "—" },
          { q: "Pentagonal prism (25mm base, 65mm height) resting on HP on rectangular face, axis parallel to HP.", marks: 10, co: "CO3", bl: "—" },
          { q: "Isometric view of a cone (50mm base diameter, 70mm altitude) resting on HP.", marks: 10, co: "CO3", bl: "—" },
          { q: "Explain steps in sand-casting process and write defects in sand casting.", marks: 10, co: "CO4", bl: "—" },
        ]},
      { id: "beee-cat2-b1", examType: "CAT2", slot: "B1+TB1", semType: "Fall", faculty: "Dr. Raghuraman D R S et al. (Closed Book)", marks: 50, duration: "90 mins", track: "Mechanical/Drawing",
        questions: [
          { q: "Redraw given figure and dimension as per BIS standards.", marks: 10, co: "CO3", bl: "BL3" },
          { q: "Draw orthographic views based on a specified isometric view with given front-view orientation arrow.", marks: 10, co: "CO3", bl: "BL3" },
          { q: "Hexagonal pyramid (25mm base, 60mm axis), base edge inclined 45° to VP, axis perpendicular to HP — top & front view.", marks: 10, co: "CO3", bl: "BL3" },
          { q: "Isometric view of a cone (50mm base diameter, 75mm height) resting on HP.", marks: 10, co: "CO3", bl: "BL3" },
          { q: "Explain extrusion manufacturing process with neat sketches.", marks: 10, co: "CO4", bl: "BL4" },
        ]},
      { id: "beee-cat2-b2", examType: "CAT2", slot: "B2+TB2", semType: "Fall", faculty: "Dr Velu M et al. (Closed Book)", marks: 50, duration: "90 mins", track: "Mechanical/Drawing",
        questions: [
          { q: "List 5 dimensioning mistake types in an incorrectly dimensioned object; dimension correctly per BIS.", marks: 10, co: "CO3", bl: "BL2" },
          { q: "Draw orthographic projections (FV/TV/RHS) of Figure-1, first-angle projection method.", marks: 10, co: "CO3", bl: "BL3" },
          { q: "Hexagonal prism (25mm base, 65mm height) resting on HP on rectangular face, axis parallel to HP, perpendicular to VP.", marks: 10, co: "CO3", bl: "BL3" },
          { q: "Isometric view of a cone (60mm base diameter, 85mm height) resting on HP.", marks: 10, co: "CO3", bl: "BL3" },
          { q: "(a) List casting defects + remedies. (b) Explain shielded metal arc welding (SMAW) process schematically.", marks: 10, co: "CO4", bl: "BL3" },
        ]},
      { id: "beee-cat2-c2", examType: "CAT2", slot: "C2+TC2", semType: "Fall", faculty: "Dr. A. Vinoth Jebaraj et al. (Closed Book)", marks: 50, duration: "90 mins", track: "Mechanical/Drawing",
        questions: [
          { q: "Identify incorrect dimensioning in Fig.1; redraw to full size per Indian Standards.", marks: 10, co: "CO3", bl: "BL3" },
          { q: "Hexagonal prism (20mm side, 60mm height) on hexagonal face, axis parallel VP, perpendicular HP — projections.", marks: 10, co: "CO3", bl: "BL3" },
          { q: "First-angle projection: front view, top view, right-side view from pictorial object.", marks: 10, co: "CO3", bl: "BL3" },
          { q: "Cylinder (55mm dia, 65mm height) on HP, axis parallel to VP, perpendicular to HP — isometric view.", marks: 10, co: "CO3", bl: "BL3" },
          { q: "(i) Purpose of pattern, core, riser in casting. (ii) Compare direct vs indirect extrusion with sketches.", marks: 10, co: "CO4", bl: "BL2" },
        ]},
    ],
  },
  {
    code: "BAMAT101",
    name: "Multivariable Calculus and Differential Equations",
    semester: 1,
    school: "School of Advanced Sciences",
    color: "#2e4a8a",
    topicWeightage: [
      { topic: "Change of order of integration (double integrals)", weight: 95, frequency: "Every CAT1 paper" },
      { topic: "Lagrange's multipliers (constrained optimization)", weight: 90, frequency: "Every CAT1 paper" },
      { topic: "Taylor's series expansion (2-variable functions)", weight: 88, frequency: "Every CAT1 paper" },
      { topic: "Functional dependence (Jacobians)", weight: 85, frequency: "Every CAT1 paper" },
      { topic: "Double integrals over bounded regions (Cartesian)", weight: 82, frequency: "Common in CAT1" },
      { topic: "Polar/cylindrical/spherical coordinate conversion (multiple integrals)", weight: 93, frequency: "Every CAT2 paper" },
      { topic: "Conservative vector fields & scalar potential functions", weight: 88, frequency: "Every CAT2 paper" },
      { topic: "Green's theorem (verification + evaluation)", weight: 85, frequency: "Every CAT2 paper" },
      { topic: "Second-order ODEs — RLC circuit charge/current problems", weight: 90, frequency: "Every CAT2 paper, standalone Q5" },
      { topic: "Directional derivatives", weight: 70, frequency: "Common in CAT2" },
      { topic: "Stokes' theorem", weight: 45, frequency: "Occasional CAT2" },
      { topic: "Critical points & classification (saddle points)", weight: 40, frequency: "Occasional CAT1/CAT2" },
    ],
    predictedImportant: [
      "Change order of integration + evaluate — the single most consistent CAT1 question, appears as Q5 in nearly every slot.",
      "Lagrange's multipliers optimization (box/surface area or temperature extremum problem) — guaranteed in CAT1.",
      "Taylor series expansion of a 2-variable function up to 3rd degree around a given point — fixed-format CAT1 question.",
      "Functional dependence check via Jacobian, then derive the relation between u, v, (w) — recurring CAT1 opener.",
      "Convert double/triple integral to polar, cylindrical, or spherical coordinates and evaluate — dominant CAT2 question type.",
      "RLC circuit modeled as 2nd-order ODE — find charge q(t) and current i(t) — guaranteed CAT2 closer, worth memorizing the auxiliary-equation method cold.",
      "Verify a vector field is conservative (curl = 0) and find its scalar potential function — recurring CAT2 question, often framed as a robotics/VR word problem.",
    ],
    papers: [
      { id: "bmat-cat1-b1", examType: "CAT1", slot: "B1+TB1", semType: "Fall", faculty: "School of Advanced Sciences", marks: 50, duration: "90 mins",
        questions: [
          { q: "Check functional dependence of u=x+y+2z, v=x-2y+z, w=-3y²+3z²+6xy+8yz+2xz; find relation if dependent.", marks: 10, co: "1", bl: "BL1" },
          { q: "Find Taylor's series expansion of f(x,y)=eˣsiny around (1, π/2), up to third degree terms.", marks: 10, co: "1", bl: "BL2" },
          { q: "Using Lagrange's multipliers, find highest/lowest temperature on sphere x²+y²+z²=10 for f=200x²y²z.", marks: 10, co: "1", bl: "BL3" },
          { q: "Evaluate ∬xy dx dy over region enclosed by x-axis, line x+y=4, and parabola x²=2y.", marks: 10, co: "2", bl: "BL2" },
          { q: "Evaluate ∫₀²∫ₓ^(x+2)(x+y) dy dx by changing the order of integration.", marks: 10, co: "2", bl: "BL3" },
        ]},
      { id: "bmat-cat1-b2", examType: "CAT1", slot: "B2+TB2", semType: "Fall", faculty: "School of Advanced Sciences", marks: 50, duration: "90 mins",
        questions: [
          { q: "Find Taylor's expansion of √(1+x+y²) in powers of (x-1) and y up to 2nd degree; compute f(1.1, 0.9).", marks: 10, co: "1", bl: "BL1" },
          { q: "Find volume of greatest rectangular parallelopiped inscribed in ellipsoid x²/a²+y²/b²+z²/c²=1.", marks: 10, co: "1", bl: "BL2" },
          { q: "(a) Find du/dt via chain rule. (b) Check functional relation of u=(x+y)/(1-xy), v=tan⁻¹x+tan⁻¹y.", marks: 10, co: "1", bl: "BL3" },
          { q: "(a) Evaluate ∫₀¹∫ₓ^√x(x²+y²) dydx. (b) Evaluate ∬x² dxdy over region bounded by y=x and y=x².", marks: 10, co: "2", bl: "BL3" },
          { q: "Change order of integration and evaluate ∫₀ᵃ∫_(x²/a)^(2a-x) xy dydx.", marks: 10, co: "2", bl: "BL3" },
        ]},
      { id: "bmat-cat1-d1", examType: "CAT1", slot: "D1+TD1", semType: "Fall", faculty: "Dr. K. Palanivel", marks: 50, duration: "90 mins",
        questions: [
          { q: "Check functional dependence of u=x+y+z, v=x²+y²+z², w=x³+y³+z³-3xyz; find relation.", marks: 10, co: "1", bl: "BL1" },
          { q: "Expand f(x,y)=eˣcosy at (1, π/4) up to third-degree terms using Taylor series.", marks: 10, co: "1", bl: "BL2" },
          { q: "Open-top rectangular box, 256 cubic feet — find dimensions for least material using Lagrange's multipliers.", marks: 10, co: "1", bl: "BL3" },
          { q: "(a) Evaluate ∬xy dxdy over quadrant of circle x²+y²=a². (b) Find area between parabolas y²=4ax, x²=4ay.", marks: 10, co: "2", bl: "BL3" },
          { q: "Evaluate ∫₀¹∫ₓ^(2-x)(x/y) dydx by changing order of integration; sketch the graph.", marks: 10, co: "2", bl: "BL3" },
        ]},
      { id: "bmat-cat1-d2", examType: "CAT1", slot: "D2+TD2", semType: "Fall", faculty: "School of Advanced Sciences", marks: 50, duration: "90 mins",
        questions: [
          { q: "If u=(x+y)/(x-y), v=xy/(x-y)² verify functional dependence; find the relation.", marks: 10, co: "1", bl: "BL2" },
          { q: "Expand log(1+x+y) about (0,0) up to third term using Taylor's series.", marks: 10, co: "1", bl: "BL2" },
          { q: "Thin closed box, one edge = twice another, volume 72m³ — find least surface area using Lagrange's multipliers.", marks: 10, co: "1", bl: "BL3" },
          { q: "Evaluate ∬(x-y)dxdy over region bounded by x=y² and x=y²/2+1; sketch the region.", marks: 10, co: "2", bl: "BL3" },
          { q: "Change order of integration in ∫₀¹∫ᵧ^(2-y) xy dxdy and evaluate.", marks: 10, co: "2", bl: "BL3" },
        ],
        hasAnswerKey: true },
      { id: "bmat-cat1-e1", examType: "CAT1", slot: "E1+TE1", semType: "Fall", faculty: "School of Advanced Sciences", marks: 50, duration: "90 mins",
        questions: [
          { q: "(a) Find du/dt at t=2 for u=sin(x/y), x=eᵗ, y=t². (b) Verify ∂²f/∂x∂y=∂²f/∂y∂x for f(x,y)=log(2x+3y).", marks: 10, co: "1", bl: "BL2" },
          { q: "Expand f(x,y)=sin(xy) in powers of (x-1), (y-π/2) up to third degree.", marks: 10, co: "1", bl: "BL2" },
          { q: "Company manufacturing cost f(x,y)=5x²+2xy+3y²+800 with x+y=39 — find minimum production cost.", marks: 10, co: "1", bl: "BL2" },
          { q: "Evaluate ∬(x²+y²)dydx over area bounded by x²=y, x=1, x=2 about x-axis.", marks: 10, co: "2", bl: "BL3" },
          { q: "Change order of integration in ∫₀¹∫ᵧ^(2-y) xy dxdy and evaluate the integral value.", marks: 10, co: "2", bl: "BL3" },
        ]},
      { id: "bmat-cat1-e2", examType: "CAT1", slot: "E2+TE2", semType: "Fall", faculty: "School of Advanced Sciences", marks: 50, duration: "90 mins",
        questions: [
          { q: "Show u=x+y+z, v=x²+y²+z²-2xy-2yz-2zx, w=x³+y³+z³-3xyz are functionally related; find the relation.", marks: 10, co: "1", bl: "BL3" },
          { q: "Second-order Taylor series approximation of f(x,y)=xy²+ycos(x-y) about (2,1).", marks: 10, co: "1", bl: "BL1" },
          { q: "(a) Find/classify critical points of f(x,y)=x³-3xy². (b) Find hottest point on ellipsoid 4x²+y²+4z²=16 with given temp function.", marks: 10, co: "2", bl: "BL4" },
          { q: "Evaluate ∬(7x²+14y)dA over region bounded by x=2y² and x=8, both integration orders.", marks: 10, co: "2", bl: "BL1" },
          { q: "Evaluate ∫₀^∞∫₀ˣ xe^(-x²/y) dy dx.", marks: 10, co: "2", bl: "BL2" },
        ],
        hasAnswerKey: true },
      { id: "bmat-cat2-b1", examType: "CAT2", slot: "B1+TB1", semType: "Fall", faculty: "Common B1 slot", marks: 50, duration: "90 mins",
        questions: [
          { q: "Evaluate ∫₀ᵃ∫ᵧᵃ x²/√(x²+y²) dxdy by changing to polar coordinates.", marks: 10, co: "2", bl: "BL2" },
          { q: "Evaluate ∫₀¹∫₀^√(1-x²)∫₀^√(1-x²-y²) dzdydx/√(1-x²-y²) by changing to spherical coordinates.", marks: 10, co: "2", bl: "BL2" },
          { q: "Show vector field F=xi+3yj+zk is conservative; find scalar potential; explain robotics application.", marks: 10, co: "3", bl: "BL3" },
          { q: "Verify Green's theorem for ∮(2xydx-y²dy) where C bounds ellipse 3x²+4y²=12.", marks: 10, co: "3", bl: "BL2" },
          { q: "RLC circuit (L=0.1H, R=20Ω, C=25µF) — find charge q and current i at any time t, given q(0)=0.05C.", marks: 10, co: "4", bl: "BL3" },
        ]},
      { id: "bmat-cat2-b2", examType: "CAT2", slot: "B2+TB2", semType: "Fall", faculty: "Common B2 slot (Open Book)", marks: 50, duration: "90 mins",
        questions: [
          { q: "Evaluate ∬√(9-x²-y²)dA over region bounded by circle x²+y²=9, by converting to polar coordinates.", marks: 10, co: "2", bl: "BL2" },
          { q: "Evaluate ∭(x²+y²)dV by converting to cylindrical coordinates, V: x²+y²≤4, 0≤z≤3.", marks: 10, co: "2", bl: "BL3" },
          { q: "(a) Directional derivative of f=xy²+yz²+zx² along tangent to curve x=t,y=t²,z=t³ at (1,1,1). (b) Show robotics potential field F is conservative; find scalar potential.", marks: 10, co: "3", bl: "BL2" },
          { q: "(a) VR haptic device force field — find work done along path y²=x from (0,0) to (1,1). (b) Verify Green's theorem for a triangular region.", marks: 10, co: "3", bl: "BL3" },
          { q: "RLC circuit (R=40Ω, L=1H, C=16×10⁻⁴F), free oscillations, zero initial charge/current — find q(t), i(t).", marks: 10, co: "4", bl: "BL3" },
        ],
        hasAnswerKey: true },
      { id: "bmat-cat2-d1", examType: "CAT2", slot: "D1+TD1", semType: "Fall", faculty: "Common Slot QP (Open Book)", marks: 50, duration: "90 mins",
        questions: [
          { q: "Use polar coordinates to evaluate ∬e^(1-x²-y²)dA, R in 4th quadrant between x²+y²=16 and x²+y²=36.", marks: 10, co: "2", bl: "BL3" },
          { q: "Use spherical coordinates to evaluate ∭x²dv, R inside x²+y²+z²=36 and z=-√(3x²+3y²).", marks: 10, co: "2", bl: "BL3" },
          { q: "Vector field F₁=(ax²y+z³)i+(x³+byz²)j+(cy²z+3xz²)k — find a,b,c for irrotational F₂; find potential φ.", marks: 10, co: "3", bl: "BL2" },
          { q: "Verify Stokes' Theorem for F=yi+xzj+x²k over a triangular pixel region cut from plane x+y+z=1.", marks: 10, co: "3", bl: "BL3" },
          { q: "Form ODE for series RLC circuit (R=20Ω, L=10H, C=5F); find current response given q(0)=1, q'(0)=0.", marks: 10, co: "4", bl: "BL3" },
        ]},
      { id: "bmat-cat2-d2", examType: "CAT2", slot: "D2+TD2", semType: "Fall", faculty: "Common D2 slot", marks: 50, duration: "90 mins",
        questions: [
          { q: "Find volume under paraboloid z=x²+y² above region D (upper half between circles r=1 and r=2), using polar coordinates.", marks: 10, co: "2", bl: "BL3" },
          { q: "Volume of material under paraboloid z=-x²-y²+9 over a circular wall boundary of radius 1.", marks: 10, co: "2", bl: "BL3" },
          { q: "Fluid velocity field F=(3x²-3y²)i-6xyj — check compression/rotation at P(1,2); find pressure if conservative.", marks: 10, co: "3", bl: "BL3" },
          { q: "Using Green's theorem, show flux around boundary = source inside, for F=(6y+x)i+(y+2x)j over circle radius 2 centered (2,3).", marks: 10, co: "3", bl: "BL3" },
          { q: "Find steady-state current in RLC circuit (R=24Ω, L=1.2H, C=1/90 F), Q=0.05, I=0 at t=0.", marks: 10, co: "4", bl: "BL3" },
        ]},
    ],
  },
  {
    code: "BACHY105",
    name: "Applied Chemistry",
    semester: 2,
    school: "School of Advanced Sciences",
    color: "#7a1f3d",
    topicWeightage: [
      { topic: "Thermodynamics & kinetics", weight: 88, frequency: "Every CAT1" },
      { topic: "Electrochemistry & energy devices (batteries, fuel cells)", weight: 85, frequency: "Every CAT1/CAT2" },
      { topic: "Nanomaterials & superconductors", weight: 75, frequency: "Common in CAT1" },
      { topic: "Magnetism", weight: 60, frequency: "Occasional" },
      { topic: "Spectroscopy & XRD", weight: 70, frequency: "Common in CAT2/FAT" },
    ],
    predictedImportant: [
      "Energy devices (battery types, fuel cell working) — recurring CAT1/CAT2 anchor question.",
      "Electrochemistry numerical/conceptual problems — consistent presence across all CATs.",
      "Nanomaterials synthesis & properties — frequent CAT1 theory question.",
      "Spectroscopy/XRD principle and application — expect at least one FAT question.",
    ],
    papers: [],
    note: "Confirmed and topic-summarized in an earlier session (8 papers: CAT1 D1/D2/F1/F2/G1/G2, CAT2 G1, FAT F1). Full question text wasn't carried into this session's context, so only topic-level data is shown here.",
  },
  {
    code: "BACSE105",
    name: "Design and Analysis of Algorithms",
    semester: 2,
    school: "School of Computer Science Engineering",
    color: "#1f4a7a",
    topicWeightage: [
      { topic: "Recurrence relations & complexity analysis", weight: 90, frequency: "Every CAT1" },
      { topic: "Trees / BST / AVL / Heaps / Hashing", weight: 88, frequency: "Every CAT1/CAT2" },
      { topic: "Graph algorithms (shortest path, MST, traversal)", weight: 92, frequency: "Every CAT2" },
      { topic: "Dynamic Programming", weight: 85, frequency: "Common in CAT2" },
      { topic: "NP-completeness", weight: 65, frequency: "Common in CAT2/FAT" },
      { topic: "Stacks / Queues / Linked Lists", weight: 70, frequency: "Common in CAT1" },
    ],
    predictedImportant: [
      "Recurrence relation solving (Master theorem / substitution) — guaranteed CAT1 opener.",
      "Graph algorithm tracing (Dijkstra/Prim/Kruskal) — dominant CAT2 question.",
      "DP problem solving (knapsack-style or similar) — recurring CAT2/FAT staple.",
      "NP-completeness proof/reduction — likely FAT-level question.",
    ],
    papers: [],
    note: "Confirmed and topic-summarized in an earlier session. Full question text wasn't carried into this session's context, so only topic-level data is shown here.",
  },
  {
    code: "BACSE103",
    name: "Computation Structures",
    semester: 2,
    school: "School of Computer Science Engineering",
    color: "#8a6a1f",
    topicWeightage: [
      { topic: "Boolean algebra & combinational circuits", weight: 90, frequency: "Every CAT1" },
      { topic: "Sequential circuits & FSMs", weight: 85, frequency: "Every CAT1/CAT2" },
      { topic: "Number systems", weight: 70, frequency: "Common in CAT1" },
      { topic: "CPU architecture & ILP", weight: 80, frequency: "Common in CAT2" },
      { topic: "Memory & cache", weight: 75, frequency: "Common in CAT2" },
    ],
    predictedImportant: [
      "Combinational circuit design/minimization (K-maps) — guaranteed CAT1 question.",
      "FSM design (Mealy/Moore) — recurring CAT1/CAT2 staple.",
      "Cache performance / memory hierarchy calculation — likely CAT2 numerical question.",
      "Pipelining / ILP hazard analysis — possible FAT-level question.",
    ],
    papers: [],
    note: "Confirmed and topic-summarized in an earlier session. Full question text wasn't carried into this session's context, so only topic-level data is shown here.",
  },
  {
    code: "BACSE104",
    name: "Statements of Object Oriented Programming (SOOP)",
    semester: 2,
    school: "School of Computer Science Engineering",
    color: "#3d7a1f",
    topicWeightage: [
      { topic: "C fundamentals (pointers, structures)", weight: 80, frequency: "Common in CAT1" },
      { topic: "OOP concepts in C++ (classes, objects)", weight: 90, frequency: "Every CAT1/CAT2" },
      { topic: "Inheritance & Polymorphism", weight: 92, frequency: "Every CAT2" },
      { topic: "Templates & STL", weight: 75, frequency: "Common in CAT2/FAT" },
    ],
    predictedImportant: [
      "Inheritance hierarchy + polymorphism (virtual functions) program-writing question — guaranteed CAT2 anchor.",
      "Pointer/structure manipulation program in C — recurring CAT1 staple.",
      "Operator overloading or template-based program — likely CAT2/FAT question.",
      "STL container usage program — possible FAT question.",
    ],
    papers: [],
    note: "Confirmed and topic-summarized in an earlier session. Full question text wasn't carried into this session's context, so only topic-level data is shown here.",
  },
  {
    code: "BMAT202L",
    name: "Probability and Statistics",
    semester: 2,
    school: "School of Advanced Sciences",
    color: "#7a3d1f",
    topicWeightage: [
      { topic: "Descriptive statistics (mean, SD, variance, CV)", weight: 80, frequency: "Common in CAT1" },
      { topic: "Discrete probability distributions (PMF, Binomial)", weight: 88, frequency: "Every CAT1" },
      { topic: "Joint distributions, correlation & regression", weight: 90, frequency: "Every CAT1" },
      { topic: "Hypothesis testing (t-test, Z-test)", weight: 92, frequency: "Every CAT2" },
      { topic: "Normal distribution applications", weight: 75, frequency: "Common in CAT2" },
      { topic: "MGF & sampling theory", weight: 60, frequency: "Common in CAT2" },
    ],
    predictedImportant: [
      "Joint density function problems (marginal/conditional, independence check) — guaranteed CAT1 staple.",
      "Correlation & regression (both directions, estimating from coefficients) — recurring CAT1 anchor.",
      "Hypothesis testing — t-test or Z-test for means/proportions — dominant, near-certain CAT2 question.",
      "Binomial distribution application (fair/unfair game framing) — common CAT1 question.",
      "Normal distribution real-world application (warranty, burn-out time style) — likely CAT2 question.",
    ],
    papers: [],
    note: "Confirmed and topic-summarized in an earlier session. Full question text wasn't carried into this session's context, so only topic-level data is shown here.",
  },
];

// Helper: flat list of all papers with subject info attached
function getAllPapers() {
  const all = [];
  SUBJECTS.forEach(s => {
    (s.papers || []).forEach(p => {
      all.push({ ...p, subjectCode: s.code, subjectName: s.name, subjectColor: s.color, semester: s.semester });
    });
  });
  return all;
}

function getSubject(code) {
  return SUBJECTS.find(s => s.code === code);
}
